### ISSUE TITLE
Brand support.

### ISSUE THREAD

**Issue by TheMinersPond** [ubiq/donations#1]
Hello, I am putting together a mining community and would like to support your coin. Specifically I am looking for Ubiq approved icons and marketing material, as well as any guidelines. TheMinersPond Ubiq pool is currently up, as in functional. But I would like to "brand" it, as in I would like to put a logo next to the links on the pool, forums and possibly more depending on what types of material you can provide. I would like to brand the whole Ubiq pool frontend, but that is a future project, depending on materials and permissions granted. I just want my site polished and ready for the grand opening soon. I feel as if I would be doing Ubiq a disservice by launching with branding for others but not Ubiq.

I searched everywhere, but could not find any public relations or media packages available. I don't want to use your image/s with out your permission. 

I figure this is a good place to ask, as it is basically free advertising (donation) having your logo and brand plastered on the Ubiq pool frontend. There is nothing better than brand recognition. 

Plus, this is something simple you can throw together fairly quick and easy, and can increase your brand presence immeasurably. Start with a folder of pictures, logos and icons then work on your guidelines later.

Thank you for your time,
TheMinersPðnd

**Comment by jyap808** [comment]
Hi, come chat to us in Discord

https://discord.gg/HF6vEGF
